var mydata = {
  points: {
    clifton_commons: {
      name: "Clifton Commons",
      coords: "42.862952, -73.820139", 
      intersection: false,
      popup: {
        title: "Clifton Commons",
        text: "This is the go to place in Clifton Park for all ages. It has baseball, soccer fields, two ice rinks (excellent for snowball fights in summer, ice hockey, and ice skating), basketball courts, an amazing playground, and an amphitheatre.<ul><li>Restrooms Available<li>Pet friendly - Dogs must be on a leash</li><li>Acreage: 81</li><li>Hours: dawn to dusk</li><li>Parking: 🚙🚙🚙</li><li>Website: <a href='https://www.cliftonpark.org/index.php/departmen?ts/parks-recreation-community-affairs/parks/' target='_blank'>https://www.cliftonpark.org/index.php/departments/parks-recreation-community-affairs/parks/</a></li></ul>",
        image: "https://www.cliftonpark.com/hot-spots/clifton-commons/images/clifton-common.jpg",
      },
    },
    boyack: {
      name: "Boyack Road Park",
      coords: "42.810647, -73.788074",
      intersection: false,
      popup: {
        title: "Boyack Road Park",
        text: "This is a nice and quiet park. It’s very clean and safe, and has many trails and sidewalks. It's a great place to take a stroll as there is a walking path. Features include: a basketball court, a baseball field, a tennis court, and a playground.<al><li>Pet friendly - Dogs must be on leash</li><li>Acreage: unknown</li><li>Hours: Dawn to dusk</li><li>Parking: 🚙</li></al>",   
        image: "pics/boyackroaddone.jpg",
      },
    },
    kinns: {
      name: "Kinns Road Park",
      coords: "42.887775, -73.810880",
      intersection: false,
      popup: {
        title: "Kinns Road Park",
        text: "This beautiful pine forest has lots to offer. Many walking trails weave over hills and streams. Picnic tables are located near the entrance. Great for walking, hiking, orienteering, and picnicking. During winter months, volunteers typically groom trails for cross-country skiing. Snowshoeing is also welcome.<ul><li>Letterboxes</li><li>Pet friendly - dogs can be off-leash with a special permit</li><li>Acreage: 64</li><li>Hours: dawn to dusk</li><li>Parking: 🚙 (plus bike racks)</li></ul>",
        image: "pics/MainEntrance_KinnsRddone.jpg",
      },
    },
    dwaas: {
      name: "Dwaas Kill Nature Preserve", 
      coords: "42.895197, -73.787504",
      intersection: false,
      popup: {
        title: "Dwaas Kill Nature Preserve",
        text: "Established in 2005, the Dwaas Kill Nature Preserve is ceated mostly of untouched natural habitat that plays a key role in the health of this area’s ecosystem and provides a home for many plants and animals. This preserve is perfect for hiking, fishing, snowshoeing, and cross-country skiing.<ul><li>Acreage: 240</li><li>Hours: 5:30am to 10:00pm</li><li>Parking: 🚙</li></ul>",   
        image: "https://anationofmoms.com/wp-content/uploads/2018/09/DwaasKill4-1200x800.jpg",
      },
    },
    garnsey: {
      name: "Garnsey Park",
      coords: "42.868203, -73.871072", 
      intersection: false,
      popup: {
        title: "Garnsey Park",
        text: "This park has meadows, a ridgeline, two ponds, a wetland, smaller trails, and a main 2 mile loop trail. It is great for walking, hiking, cross-country skiing, and trail running. Garnsey Park also has the second highest point in Rexford and it is the site of the Rexford Veterans Memorial. Also, it used to be a farm that grew berries.<ul><li>Berry-picking</li><li>Storyboards</li><li>Letterboxes</li><li>Pet friendly - Dogs must be on leash</li><li>Acreage: 150</li><li>Hours: 5:30am to 10pm</li><li>Parking: 🚙🚙(plus bike racks)</li></ul>",
        image: "pics/garnseydone.jpg",
      },
    },
    george_smith: {
      name: "George T. Smith Park",
      coords: "42.898944, -73.818250", 
      intersection: false,
      popup: {
        title: "George T Smith Park",
        text: "This park offers plenty of shade to keep the playground equipment from getting too hot during the summer months. There is a good mix of new and classic equipment. There is also an area for small toddlers which is a huge perk. There are also tennis courts, basketball, and walking trails.<ul><li>Not pet friendly</li><li>Hours: 5:00AM to 10:00PM</li><li>Parking: 🚙🚙</li></ul>",
        image: "pics/GeorgeTSmithparkdone.jpg",
      },
    },
    longkill: {
      name: "Longkill Park",
      coords: "42.917288, -73.821698",
      intersection: false,
      popup: {
        title: "Longkill Park",
        text: "It has baseball fields, a basketball court, tennis courts, soccer fields, and a playground.  It is great for sledding as it has a big hill.<ul><li>Acreage: unknown</li><li>Hours: 5:00AM to 9:00PM</li></ul>",
        image: "pics/Longkill_Park_playareadone.jpg",
      },
    },
    ushers: {
      name: "Usher's Road State Park",
      coords: "42.912530, -73.772139",
      intersection: false,
      popup: {
        title: "Usher's Road State Park",
        text: "Usher's Road State Park is a large forest which has two main trails which offers a number of activity options and is accessible year-round. It is great for mountain biking, hiking, cross-country skiing, bird watching, and snowshoeing.<ul><li>Acreage: 122</li><li>Hours: Dawn to dusk</li></ul>",
        image: "https://uncoveringnewyork.com/wp-content/uploads/2020/04/Ushers-Road-State-Forest-5465-600x450.jpg",
      },
    },
    ushers_zim: {
      name: "Usher's Road State Park at Zim Smith Trail",
      coords: "42.912530, -73.772139",
      intersection: false,
      popup: {
        title: "Usher's Road State Park at Zim Smith Trail",
        text: "Usher's Road State Park is a large forest which has two main trails. The park offers a number of activity options and is accessible year-round. It is great for mountain biking, hiking, cross-country skiing, bird watching, and snowshoeing.<ul><li>Acreage: 122</li><li>Hours: dawn to dusk</li></ul>",
        image: "https://uncoveringnewyork.com/wp-content/uploads/2020/04/Ushers-Road-State-Forest-5465-600x450.jpg",
      },
    },
    skano: {
      name: "Skano Elementary",
      coords: "42.86151126824017, -73.81072185034046", 
      intersection: false,
      popup: {
        title: "Skano Elementary School",
        text: "This playground is located directly to the rear of the school and is one of the 8 elementary schools in the Shenendehowa CSD. This playground has at least two pieces of equipment that can be used by children with physical restrictions. Also Skano’s perimeter of the park is covered with rubberized matting that is overlaid with a soft, artificial fibrous material that looks like straw. There are also swings and slides.<ul><li> Pet friendly - Dogs must be on leash.</li><li>Parking: 🚙🚙🚙</li></ul>",
        image: "pics/Skanodone.jpg",
      },
    },
    hayes_liberty: {
      name: "Hayes Nature Park at Liberty Way",
      coords: "42.826092, -73.781111",
      intersection: false,
      popup: {
        title: "Hayes Nature Park at Liberty Way",
        text: "The Hayes Nature Park Trail is a trail loop that is around 1.4 miles long, and over a mile of that is ADA-accessible. There are two entrances: this one at Liberty Way and another at Moe Road. It is nice for all ages and great for hiking, walking, running, biking, cross-country skiing, and snowshoeing.Though this trail is made of gravel the trails are wheelchair accessible. There are no handicapped parking spots in the lot.<ul><li>Letterboxes</li><li>Storyboards</li><li>Pet friendly - Dogs must be on leash</li><li>Acreage: 48</li><li>Hours: dawn to dusk</li><li>Parking: 🚙 (plus bike racks)</li></ul>",   
        image: "https://capitaldistrictmoms.com/wp-content/uploads/2020/06/IMG_2342.jpg",
      },
    },
    hayes_moe: {
      name: "Hayes Nature Park at Moe Road",
      coords: "42.826060, -73.789512",
      intersection: false,
      popup: {
        title: "Hayes Nature Park at Moe Road",
        text: "The Hayes Nature Park Trail is a trail loop that is around 1.4 miles long, and over a mile of that is ADA-accessible. There are two entrances: this one at at Moe Road and another at Liberty Way. It is nice for all ages and is an easy hike. Great for hiking,walking, cross-country skiing, snowshoeing, and running. Though the trail is gravel, it is relatively smooth and wheelchair friendly but there are no handicapped spots in the parking lot. There is a bike rack and picnic table at this entrance. The Clifton Park/Halfmoon Public Library has sponsored a book reading by placing placards along the trail with pages from children's books starting at this entrance.<ul><li>Letterboxes</li><li>Storyboards</li><li>Pet friendly - Dogs must be on leash</li><li>Acreage: 48</li><li>Hours: dawn to dusk</li><li>Parking: 🚙 (plus bike racks)</li></ul>",
        image: "https://capitaldistrictmoms.com/wp-content/uploads/2020/06/IMG_2342.jpg",
      },
    },
    northwoods_north: {
      name: "North Woods Preserve at Shadow Wood Way",
      coords: "42.922389, -73.810184",
      intersection: false,
      popup: {
        title: "North Woods Preserve  - at Shadow Wood Way",
        text: "The North Woods Nature Preserve is a forest in Country Knolls. It has trails and a stream, and a pretty pond with benches. Great for hiking, walking, snowshoeing, bird watching,nature trips, and picnicking. There are many mosquitoes in the summer, so be prepared with plenty of bug spray and a map.<ul><li>Pet friendly - Dogs must be on leash</li><li>Acreage: 80</li><li>Hours: 6am to 9pm</li><li>Parking: 🚙 (street parking)</li></ul>",
        image: "https://heritagecb.com/wp-content/uploads/2019/09/extra_large_aff33c2807ca5df8a83fe85dddb0e279.jpg",
      },
    },
    northwoods_water_tower: {
      name: "North Woods Preserve - near the water tower)",
      coords: "42.918266, -73.818175",
      intersection: false,
      popup: {
        title: "North Woods Preserve - near the water tower",
        text: "This entrance is on Blue Spruce Lane. There is a water tower, and near that water tower is an entrance that can be accessed by walking or biking. The North Woods Nature Preserve is a forest in Country Knolls. It has trails through the forest, a stream, and a pretty pond with benches near. Great for hiking, walking, snowshoeing, bird watching, nature trips, and picnicking. There are many mosquitoes and off shoots, so be prepared with plenty of bug spray and a map.<ul><li>Pet friendly - Dogs must be on leash</li><li>Acreage: 80</li><li>Hours: 6am to 9pm</li><li>Parking: 🚙 (street parking)</li></ul>",   
        image: "https://heritagecb.com/wp-content/uploads/2019/09/extra_large_aff33c2807ca5df8a83fe85dddb0e279.jpg",
      },
    },
    veterans: {
      name: "Veterans Memorial Park",
      coords: "42.902923, -73.846200",
      intersection: false,
      popup: {
        title: "Veterans Memorial Park",
        text: "This park can be found at Elks Trail and has softball fields and a pavilion. There are also beautiful wetlands and woodlands behind the ballfields. There are natural surface trails here where you can hike, walk, snowshoe, country ski, and just observe the wetlands. Trails are not groomed regularly and it is muddy due to the wetlands.<ul><li>Pet friendly - Dogs must be on leash</li><li>Acreage: 141</li><li>Hours: 6:00am to 9:00pm</li><li>Parking: 🚙🚙🚙</li></ul>",   
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/27292310/extra_large_e3550951162c8b91228e3f6dd3b18dee.jpg",
      },
    },
    woodcock: {
      name: "Woodcock Preserve",
      coords: "42.886517, -73.831001",
      intersection: false,
      popup: {
        title: "Woodcock Preserve",
        text: "This preserve is made up of groomed trails with woodland and swamp areas. There are around 2.4 miles of trails on the property which are maintained by volunteers. There is wildlife here, with animals such as deer, coyote, hawks, and owls. The preserve is named after the small and chubby birds that dwell there.Bikes not permitted.<ul><li>Pet friendly - dogs must be on leash</li><li>Acreage: 72</li><li>Hours: sunrise to sunset</li><li>Parking:🚙</li><li>Website: <a href='https://www.saratogaplan.org/explore/public-preserves-trails/woodcock-preserve/' target='_blank'>https://www.saratogaplan.org/explore/public-preserves-trails/woodcock-preserve/</a></li></ul>",   
        image: "pics/WoodcockPreservedone.jpg",
      },
    },
    west_sky: {
      name: "West Sky Natural Area",
      coords: "42.819471, -73.796058",
      intersection: false,
      popup: {
        title: "West Sky Natural Area",
        text: "The West Sky Natural Area is a preserved open space with a 0.6-mile long trail located in the Town of Clifton Park. It is wheelchair accessible. Walking paths take you through a large forest. A will also find a playground along the trail.<ul><li>Acreage: unknown</li><li>Parking: 🚙</li></ul>",   
        image: "https://curiousbynature.files.wordpress.com/2019/06/20190609_132332-sample.jpg?w=584",
      },
    },
    chango: {
      name: "Chango Elementary School",
      coords: "42.9331876262543, -73.81177158911049", 
      intersection: false,
      popup: {
        title: "Chango Elementary School",
        text: "Chango is one of the 8 elementary schools in the Shenendehowa CSD. It has a playground located behind the school. The playground has multiple swing sets, a basketball court, two four square courts, multiple slides, monkey bars, a roundabout with seats, a ramp pathway, a plastic boulder with colored stones to resemble rock climbing, wall ball area, multiple benches, spin ball, tether ball pole, and a big hill. The playground is public and available for use before and after school hours.<ul><li>Pet friendly</li><li>Acreage: unknown</li><li>School hours (currently): 9:30am to 2:30pm</li><li>Parking: 🚙🚙🚙 (plus bike racks)</li><li>Website: <a href=’https://www.shenet.org/chango-elementary/’>https://www.shenet.org/chango-elementary/</a></li></ul>",
        image: "pics/chango1done.jpg",
      },
    },
    zim_coons: {
      name: "Zim Smith Trail at Coons Crossing",
      coords: "42.919411, -73.746441",
      intersection: false,
      popup: {
        title: "Zim Smith Trail at Coons Crossing",
        text: "This 9-mile trail connects Halfmoon to Ballston Spa.The Zim Smith Trail is open for both hiking and biking, and one recommended starting point is at Shenantaha Creek Park which is located about midway along the trail.  Website: http://newyorktrailheads.com/2016/04/09/Zim-Smith-Trail.html<ul><li>Restrooms Available<li>Hours: dawn to dusk</li><li>Parking:🚙</li></ul>",
        image: "https://www.saratoga.com/images/zim-smith-trail.jpg",
      },
    },
    whipple: {
      name: "Vischer Ferry Preserve - Whipple Truss Bridge",
      coords: "42.79269109995435, -73.79578866485257",
      intersection: false,
      popup: {
        title: "Vischer Ferry Preserve - Whipple Truss Bridge",
        text: "This entrance starts with the Whipple Truss foot bridge. Trails go off in several directions after crossing the bridge - perfect for walking, running, or biking.During winter months these trails are excellent for snow shoeing and cross country skiing. Excellent for bird watching. The Clifton Park/Halfmoon Public Library has displayed story boards heading west on the path. This is a historic landmark and bridge.<ul><li>Letterboxes</li><li>Storyboards</li><li>Pet friendly - Dogs must be on leash</li><li>Hours: dawn to dusk</li><li>Parking: 🚙🚙🚙</li></ul> ",
        image: "pics/whipplebridge.jpg",
      },
    },
    ferry_road: {
      name: "Vischer Ferry Preserve - Ferry Road",
      coords: "42.79442703203684, -73.83114057011322",
      intersection: false,
      popup: {
        title: "Vischer Ferry Road Entrance",
        text: "This entrance has a kayak boat launch and fishing area. There is a wide gravel walking, running, and biking path. During winter months these trails are excellent for snow shoeing and cross country skiing.<ul><li>Letterboxes</li><li>Pet friendly - Dogs must be on leash</li><li>Hours: dawn to dusk</li><li>Parking: 🚙🚙🚙</li></ul>", 
        image: "pics/VF_FerryRoad2.jpg",
      },
    },
    clutes: {
      name: "Vischer Ferry Preserve - Clute's Dry Dock",
      coords: "42.79454979027138, -73.776604487915",
      intersection: false,
      popup: {
        title: "Vischer Ferry Preserve - Clute's Dry Dock",
        text: "This historic dry dock was established about the time the Erie Canal opened in 1825, and was probably enlarged when the canal was widened in 1842.Recently, the town of Clifton Park added a new bridge making it possible for visitors walking, running, biking access to the towpath trail. During winter months these trails are excellent for snow shoeing and cross country skiing.<ul><li><a href='https://www.shenet.org/about-us/historical-information-2/history-of-carillon-bells/' target='_blank'>One of the original carillon bell locations</a></li><li>Letterboxes</li><li>Pet friendly - dogs must be on leash</li><li>Hours: dawn to dusk</li><li>Parking: 🚙🚙🚙</li></ul>", 
        image: "pics/ClutesDryDock1.jpg",
      },
    },
    towpathLock7Lookout: {
      name: "Towpath - Lock 7 Lookout",
      coords: "42.807114, -73.841726",
      intersection: false,
      popup: {
        title: "Towpath - Lock 7 Lookout",
        text: "This is a great place to see Lock 7 and the dam. A walking, running, and biking trail starts at the parking area and heads east along the Mohawk River and eventually joins the Vischer Ferry Nature Preserve.<ul><li>Letterboxes</li><li>Storyboards</li><li>Pet Friendly - Dogs must be on leash<li>Hours: 5:00AM to 10:00PM</li><li>Parking: 🚙</li></ul>",
        image: "https://lh5.googleusercontent.com/p/AF1QipP0s9cHzwQPuFauEGp2O2qQeQNl8LJ9MOI9edOb=w408-h306-k-no",
      },
    },
    riverview: {
      name: "Towpath Trail near I-87 underpass",
      coords: "42.798794297040786, -73.76823450342494",
      intersection: true,
    },
    riverview1: {
      coords: "42.79464739032394, -73.77224198239547",
      intersection: true,
    },
    collins: {
      name: "Collins Park",
      coords: "42.864059448895496, -73.79362020354156",
      intersection: false,
      popup: { 
        title: "Collins Park",
        text: "Collins park is near the intersection of Moe Rod and Route 146. Collins has a ball field,playground, nature trail, picnic areas, pavilion, and open-space areas for a variety of sporting activities and family gatherings. Reservations for group use may be made by calling the Clifton Park Town Office of Parks, Recreation and Community Affairs.<ul><li>Restrooms Available<li>Pet Friendly - Dogs must be on leash</li><li>Acreage: 8</li><li>Hours: 5:30AM to 10:00PM</li><li>Parking: 🚙🚙🚙</li><li>Website: <a href='https://www.cliftonpark.org/departments/parks-recreation-community-affairs/parks/67-parks.html' target='_blank'>https://www.cliftonpark.org/index.php/departments/parks-recreation-community-affairs/parks/</a></li></ul>",
        image: "https://fastly.4sqi.net/img/general/200x200/GTU0KE41T0E5KGBGF5G4BPJ1DKWRWJUGH4AJFAG4F2XONR4N.jpg", 
      },
    },
    karigon: {
      name: "Karigon Elementary School",
      coords: "42.86660341268434, -73.8110663105756",
      intersection: false,
      popup: {
        title: "Karigon Elementary School",
        text: "This playground is on the Shenendehowa Main campus. The playground is located next to the school.<ul><li>Pet friendly - Dogs must be on leash </li><li>Hours: outside school hours</li><li>Parking: 🚙🚙🚙</li></ul>",
        image: "pics/Karigondone.jpg",
      },
    },
    okte: {
      name: "Okte Elementary School",
      coords: "42.81786543338188, -73.78399269342576",
      intersection: false,
      popup: {
        title: "Okte Elementary School",
        text: "Okte is one of the elementary schools not located on Shenendehowa's main campus. It is located on Crescent Road (exit 8 west of I87). A new playground is located next to the school.<ul><li>Pet friendly - Dogs must be on leash</li><li>Acreage: unknown</li><li>Hours: Outside school hours</li><li>Parking: 🚙🚙🚙</li></ul>",
        image: "pics/okte1done.jpg",
      },
    },
    orenda: {
      name: "Orenda Elementary School",
      coords: "42.866094993026415, -73.81078882334074",
      intersection: false,
      popup: {
        title: "Orenda Elementary School",
        text: "This playground is on the Shenendehowa Main campus. The playground is located next to the school.<ul><li>Pet friendly - dogs must be on leash.</li><li>Hours: outside school hours</li><li>Parking: 🚙🚙🚙</li></ul>",
        image: "pics/Orenda_closeupofequipmentdone.jpg",
      },
    },
    shatekon: {
      name: "Shatekon Elementary School",
      coords: "42.858600, -73.788538 ",
      intersection: false,
      popup: {
        title: "Shatekon Elementary School",
        text: "This playground is on the Shenendehowa Main campus. The playground is located next to the school.<ul><li>Pet friendly - Dogs must be on leash.</li><li>Hours: Outside school hours</li><li>Parking: 🚙🚙🚙</li></ul>",
        image: "pics/Shatekondone.jpg",
      },
    },
    tesago: {
      name: "Tesago Elementary School",
      coords: "42.86092522760286, -73.81081479798009",
      intersection: false,
      popup: {
        title: "Tesago Elementary School",
        text: "Tesago is one of the Shenendehowa elementary schools and has a relatively new playground, pretty fun for young children.<ul><li>Parking: 🚙🚙🚙</li></ul>",
        image: "pics/Tesago2done.jpg",
      },
    },
    balsam_moe: {
      name: "Balsam Way Natural Area at Moe Road",
      coords: "42.833044, -73.790413",
      intersection: false,
      popup: {
        title: "Balsam Way Natural Area",
        text: "Balsam Way Natural Area is parkland and a local historic site, including a multi-use trail connecting the Carlson Farms neighborhood from Moe Road to Huntwood Drive. Balsam Way Natural Area contains a 3,500-foot long multiple-use trail that continues across Balsam Way and terminates at Huntwood Drive.<ul><li>Parking: 🚙</li></ul>",
        image: "https://curiousbynature.files.wordpress.com/2016/03/cropped-dsc03681-sample.jpg",
      },
    },
    balsam_south: {
      name: "Balsam Way Natural Area at South Entrance",
      coords: "42.833044, -73.790413",
      intersection: false,
      popup: {
        title: "Balsam Way Natural Area at South Entrance",
        text: "Balsam Way Natural Area is parkland and a local historic site, including a multi-use trail connecting the Carlson Farms neighborhood from Moe Road to Huntwood Drive. Balsam Way Natural Area contains a 3,500-foot long multiple-use trail that continues across Balsam Way and terminates at Huntwood Drive.<ul><li>Parking: 🚙</li></ul>",
        image: "https://curiousbynature.files.wordpress.com/2016/03/cropped-dsc03681-sample.jpg",
      },
    },
    vanpatten_west: {
      name: "Robert Van Patten Trail west end",
      coords: "42.893169, -73.815529",
      intersection: false,
      popup: {
        title: "Robert Van Patten Trail West End",
        text: "This 1.6-mile long multi-use trail connects to Ushers Road and the intersection of Carlton Road and Van Patten Drive.",
      },
    },
    vanpatten_mid: {
      name: "Robert Van Patten Trail at Carleton Road",
      coords: "42.892763, -73.809982",
      intersection: false,
      popup: {
        title: "Robert Van Patten Trail West End",
        text: "This 1.6-mile long multi-use trail connects to Ushers Road and the intersection of Carlton Road and Van Patten Drive.",
      },
    },
    vanpatten_mid2: {
      name: "Robert Van Patten Trail at LaCosta Drive",
      coords: "42.895092, -73.798544",
      intersection: false,
      popup: {
        title: "Robert Van Patten Trail at LaCosta Drive",
        text: "This 1.6-mile long multi-use trail connects to Ushers Road and the intersection of Carlton Road and Van Patten Drive.",
      },
    },
    vanpatten_east: {
      name: "Robert Van Patten Trail East End",
      coords: "42.902282, -73.790786",
      intersection: false,
      popup: {
        title: "Robert Van Patten Trail East End",
        text: "This is a walking/running/biking/ trail that weaves in and around neighborhoods."
      },
    },
    barney: {
      name: "Barney Road Park",
      coords: "42.84823483049839, -73.80656272709444",
      intersection: false,
      popup: {
        title: "Barney Road Park",
        text: "The Barney Road Park offers a playground for children. Parking is at the Barney Road pool run by the Town of Clifton Park. The pool has lanes, slide and diving board. There is a small separate pool for very young children. There is also a par-3 golf course nearby.<ul><li>Restrooms Available</li><li>Hours: 7:30AM to 7:30PM</li></ul>",
        image: "https://cloud.travelpledge.com/UploadFiles/PotentialCourses/Photos/22187/Barney_Road_Golf-photo.jpg",
      },
    },
    halfmoon_town: {
      name: "Halfmoon Town Park",
      coords: "42.86283898889074, -73.7298350865765",
      intersection: false,
      popup: {
        title: "Halfmoon Town Park",
        text: "This park was established in 2010. It has gravel walking/biking trails, 3 playgrounds for different age groups, and baseball fields. It also has a splashpark where kids can go play in the water on a hot summer day. It's also a great place to take your dog for a walk. There's also an ice cream place that you can walk to from the park.  <ul><li>Restrooms Available<li>Pet Friendly - Dogs must be on a leash <li>Hours: 6am to 10pm<li>Parking: 🚙🚙🚙</li></ul>",
        image: "https://capitaldistrictmoms.com/wp-content/uploads/2019/05/img_4169.jpg",
      },
    },
    harris: {
      name: "Harris Park",
      coords: "42.85518645215017, -73.72527510569785",
      intersection: false,
      popup: {
        title: "Harris Park",
        text: "Harris park is a large park in Halfmoon that has a small playground and many athletic fields.<ul><li>Parking: 🚙🚙🚙🚙</li><li>One basketball court</li><li>Two tennis courts</li><li>Two volleyball courts</li><li>Two baseball fields</li><li>One soccer field</li></ul>",
        image: "https://cliftonpark.org/images/igallery/resized/1-100/foot_bridge_barney_road_executive_golf_course-75-800-600-80.jpg",
      },
    },
    locust_lane: {
      name: "Locust Lane Park",
      coords: "42.85618698285853, -73.80813010376367",
      intersection: false,
      popup: {
        title: "Locust Lane Park",
        text: "This park has a playarea for younger children, an open field and tennis courts nearby. The Locus Lane Town pool is adjacent to the park and is where visitors should park. The pool has a lanes and a diving board. There is a small pool for very young children. It also has a bathhouse. Membership to use the pool during the summer months can be obtained through teh Town of Clifton Park. Town sponsored summer camps are located here.  <ul><li>Restrooms Available<li>Parking:🚙🚙🚙🚙</li></ul>",
        image: "https://lh5.googleusercontent.com/p/AF1QipNvFYtQ5mWDdj3QmeNRvmSJH68CM3OBxiWlX7pS=w408-h544-k-no",
      },
    },
    shenantaha: {
      name: "Shenantaha Creek Park",
      coords: "42.96466672590471, -73.82408339211305",
      intersection: false,
      popup: {
        title: "Shenantaha Creek Park",
        text: "This park has basketball courts, volleyball courts, playgrounds, multiple pavilions with picnic tables that you can reserve, bathrooms, and walking paths you can take. It also has frisbee golf. Summer camps and events are held here a lot. The Zim Smith Trail goes by this park. It is also near the Indian Mortar Trail.<ul><li>Restrooms Available<li>Pet Friendly - pets must be leashed and are allowed on trails, but not allowed on active areas of the park.</li><li> Acreage: 56.1</li><li>Hours: 7:30AM to sunset</li><li>Parking:🚙🚙🚙🚙</li><li>Website: <a href='https://www.malta-town.org/Facilities/Facility/Details/3' target='_blank'>https://www.malta-town.org/Facilities/Facility/Details/3</a></li></ul>",
        image: "https://upload.wikimedia.org/wikipedia/commons/2/22/Shenantaha_Creek_Park_sign.jpg",
      },
    },
    abele: {
      name: "Abele Memorial Park",
      coords: "42.85344215408518, -73.72700845842552",
      intersection: false,
      popup: {
        title: "Abele Memorial Park",
        text: "The area of Abele Memorial Park was dedicated in honor of Jack Abele. It has a gazebo, a 9/11 memorial, benches, walkways, and a parking area. It is a nice and quiet place to relax.<ul><li>Parking: 🚙</li><li>Website: <a href='https://www.townofhalfmoon-ny.gov/parks-recreation-areas/pages/abele-memorial-park' target='_blank'>https://www.townofhalfmoon-ny.gov/parks-recreation-areas/pages/abele-memorial-park</a></li></ul>",
        image: "https://www.townofhalfmoon-ny.gov/sites/g/files/vyhlif4491/f/u71/25.jpg",
      },
    },
    burning_bush: {
      name: "Burning Bush Park",
      coords: "42.914690088423924, -73.81542568911121",
      intersection: false,
      popup: {
        title: "Burning Bush Park & Pool",
        text: "This is a nice and quiet neighborhood park. It has many trails and sidewalks. It is a great place to take a stroll or join friends for a game of ball. Features include: a basketball court, a baseball field, a tennis court, and a playground.There is a town pool next to the park. You can become a member to the pool through the Town of Clifton Park. <ul><li>Restrooms Available<li>Pet friendly</li><li>Acreage: unknown</li><li>Hours: dawn to dusk</li><li>Parking: 🚙🚙🚙</li></ul>",   
        image: "https://parksrec.egov.basgov.com/TenantContent/cliftonpark/pools/1_Pool_2.jpg",
      },
    },
    desrochers: {
      name: "Peter Desrochers Memorial Trails",
      coords: "42.912605224903004, -73.81572105783742",
      intersection: false,
      popup: {
        title: "Peter Desrocher's Memorial Trails",
        text: "This trails weave throughout the forest connecting neighborhoods.<ul><li>Pet friendly - Dogs must be on leash</li><li>Mileage: 2.1</li><li>Hours: dawn to dusk</li><li>No Parking - accessed by walkway</li></ul>",
        image: "http://1.bp.blogspot.com/-ZRVA9Va4MIo/VmC7IL6h2QI/AAAAAAAATjA/vIbhHMWasH0/s1600/IMG_8839.JPG",
      },
    },
    clifton_gardens: {
      name: "Clifton Gardens Park",
      coords: "42.84817459073375, -73.78634304096568",
      intersection: false,
       popup: {
        title: "Clifton Gardens Park",
        text: "Check back soon....more information coming.",
        image: "pics/Cliftongardens.jpg",
      },
    },
    mohawk_landing: {
      name: "Mohawk Landing Nature Preserve",
      coords: "42.82830630990719, -73.86057322338362",
      intersection: false,
       popup: {
        title: "Mohawk Landing Nature Preserve",
        text: "This truly lovely preserve is located next to Riverview Orchards.<ul><li>Pet friendly - Dogs must be on leash</li><li>Acreage: unknown</li><li>Hours: dawn to dusk</li><li>Parking 🚙🚙</li></ul>",
          image: "pics/mohawklanding.jpeg",
      },
    },
    indian_mortars: {
      name: "Indian Mortars Trail",
      coords: "42.96524770343713, -73.82209855814405",
      intersection: false,
    },
    ballston_creek: {
      name: "Ballston Creek Nature Preserve",
      coords: "42.96753289011033, -73.83382627206754",
      intersection: false,
    },
    maryjane_row: {
      name: "Mary Jane Row Dog Park",
      coords: "42.82763470195935, -73.8270528538509",
      intersection: false,
      popup: {
        title: "Mary Jane Row Dog Park",
        text: "Mary Jane Row Dog Park is a great place for your dogs to play around and have fun!<ul><li>Pet friendly - dogs can be off leash with a special permit",
      },
    },
    settlers_hill: {
      name: "Settlers Hill Natural Area",
      coords: "42.84788619159297, -73.84283109739884",
      intersection: false,
    },
    summer_hill: {
      name: "Summer Hill Natural Area",
      coords: "42.859884680966736, -73.82278450893665",
      intersection: false,
    },
    calico: {
      name: "Calico Colony Park",
      coords: "42.869387986702385, -73.81481785405826",
      intersection: false,
    },
    bernini: {
      name: "Bernini Drive Park",
      coords: "42.886946307921825, -73.79011557985342",
      intersection: false,
    },
    kimberly: {
      name: "Kimberly Court Park",
      coords: "42.80154597018642, -73.77175052669263",
      intersection: false,
    },
    spirit: {
      name: "Spirit Park",
      coords: "42.85468349453999, -73.79360558312474",
      intersection: false,
    },
    arongen: {
      name: "Arongen Elementary School",
      coords: "42.85797391428709, -73.78912573144129",
      intersection: false,
    },
    route146_waypoint1: {
      coords: "42.86274511808491, -73.77200341027563",
      intersection: true,
    },
    route146_waypoint2: {
      coords: "42.86257816941036, -73.77394334022371",
      intersection: true,
    },
    route146_waypoint3: {
      coords: "42.862509087063486, -73.77545915595046",
      intersection: true,
    },
    route146_waypoint4: {
      coords: "42.86253211452029, -73.77713990497757",
      intersection: true,
    },
    route146_waypoint5: {
      coords: "42.863355340435135, -73.78277119962628",
      intersection: true,
    },
    route146_waypoint6: {
      coords: "42.86508971457936, -73.7912887237775",
      intersection: true,
    },
    route146_waypoint7: {
      coords: "42.86717915433715, -73.79706321336758",
      intersection: true,
    },
    route146_waypoint8: {
      coords: "42.8676026752791, -73.79885922187385",
      intersection: true,
    },
    route146_waypoint9: {
      coords: "42.86794606851119, -73.80354446145465",
      intersection: true,
    },
    route146_waypoint10: {
      coords: "42.86982229286305, -73.81519241741444",
      intersection: true,
    },
    moe1: {
      coords: "42.86494777768859, -73.79458602024238",
      intersection: true,
    },
    moe2: {
      coords: "42.83287521166614, -73.79395854526223",
      intersection: true,
    },
    moe3: {
      coords: "42.83283392387654, -73.79145315076653",
      intersection: true,
    },
    moe4: {
      coords: "42.83269457740327, -73.7908549526404",
      intersection: true,
    },
    balsam1: {
      coords: "42.83466810848476, -73.79391126108541",
      intersection: true,
    },
    balsam2: {
      coords: "42.83389631526395, -73.79386499911348",
      intersection: true,
    },
    balsam3: {
      coords: "42.83377333632586, -73.79365682023634",
      intersection: true,
    },
    balsam4: {
      coords: "42.83394720301871, -73.79269110157203",
      intersection: true,
    },
    balsam5: {
      coords: "42.83396416559678, -73.79053991987128",
      intersection: true,
    },
    balsam6: {
      coords: "42.833510415030695, -73.78962624592185",
      intersection: true,
    },
    balsam7: {
      coords: "42.833544340419984, -73.78918097443423",
      intersection: true,
    },
    balsam8: {
      coords: "42.83379878024519, -73.78844656561621",
      intersection: true,
    },
    balsam9: {
      coords: "42.83319236356713, -73.78585011244097",
      intersection: true,
    },
    balsam10: {
      coords: "42.832844625437126, -73.78553784412702",
      intersection: true,
    },
    balsam11: {
      coords: "42.8317165834195, -73.78580963321173",
      intersection: true,
    },
    balsam12: {
      coords: "42.83131794710247, -73.78616238074774",
      intersection: true,
    },
    avendale: {
      coords: "42.94539701028303, -73.80916240067457",
      intersection: true,
    },
    avendale1: {
      coords: "42.94567425190748, -73.80962561208604",
      intersection: true,
    },
    avendale2: {
      coords: "42.945910538705185, -73.80972342929364",
      intersection: true,
    },
    avendale3: {
      coords: "42.946085963167924, -73.80964273009843",
      intersection: true,
    },
    avendale4: {
      coords: "42.94681808638948, -73.80879661125338",
      intersection: true,
    },
    avendale5: {
      coords: "42.94683061654273, -73.8083026343555",
      intersection: true,
    },
    avendale6: {
      coords: "42.94823039729647, -73.8072828899662",
      intersection: true,
    },
    avendale7: {
      coords: "42.94917191990331, -73.80809232735866",
      intersection: true,
    },
    avendale8: {
      coords: "42.94962656634254, -73.80824149859957",
      intersection: true,
    },
    avendale9: {
      coords: "42.95006331015703, -73.80824149859963",
      intersection: true,
    },
    avendale10: {
      coords: "42.95023131792188, -73.80809596175483",
      intersection: true,
    },
    avendale11: {
      coords: "42.95041738710604, -73.80806863989626",
      intersection: true,
    },
    avendale12: {
      coords: "42.950577371379474, -73.80800330501665",
      intersection: true,
    },
    avendale13: {
      coords: "42.95065997179315, -73.8079462854855",
      intersection: true,
    },
    avendale14: {
      coords: "42.95076170057117, -73.80791302409227",
      intersection: true,
    },
    avendale15: {
      coords: "42.95082778071097, -73.80781205200627",
      intersection: true,
    },
    avendale16: {
      coords: "42.95088516603988, -73.807674254806",
      intersection: true,
    },
    avendale17: {
      coords: "42.95100776178899, -73.80754714876774",
      intersection: true,
    },
    avendale18: {
      coords: "42.951710718366, -73.80664227422298",
      intersection: true,
    },
    avendale19: {
      coords: "42.95182331265978, -73.80652513566443",
      intersection: true,
    },
    avendale20: {
      coords: "42.95214353383801, -73.80626686631301",
      intersection: true,
    },
    avendale21: {
      coords: "42.95224166580399, -73.8061426712143",
      intersection: true,
    },
    avendale22: {
      coords: "42.95176552094283, -73.80533908775777",
      intersection: true,
    },
    avendale_i87: {
      name: "Avendale",
      coords: "42.951131, -73.803946",
      intersection: false,
    },
    avendale_path: {
      name: "Avendale",
      coords: "42.946270, -73.809771",
      intersection: false,
    },
    avendale_sage: {
      name: "Avendale",
      coords: "42.944947, -73.809368",
      intersection: false,
    },
    avendale_turn: {
      coords: "42.94553415229574, -73.8093290095648",
      intersection: true,
    },
  },
  connections: [
    ["clifton_commons","skano"],
    ["northwoods_north","northwoods_water_tower"],
    ["skano","shen_moe"],
    ["skano","shen_146"],
    ["shen_146","shen_moe"],
    ["longkill","longkill_blue_spruce"],
    ["longkill","longkill_water_tower"],
    ["ushers","ushers_zim"],
    ["kinns","kinns_canterbury"],
    ["dwaas","dwaas_trail_end"],
    ["balsam_moe","balsam_south"],
    ["hayes_moe","hayes_liberty"],
    ["new_park_east","new_park_west"],
    ["towpath_van_vranken","towpath_middle"],
    ["towpath_middle","towpath_van_vranken"],
    ["towpath_middle","towpath_ferry"],
    ["towpath_ferry","towpath_powerlines"],
    ["towpath_powerlines","towpath_lock7"],
    ["ushers_zim","zim_english"],
    ["vanpatten_west","vanpatten_mid"],
    ["vanpatten_mid","vanpatten_mid2"],
    ["vanpatten_mid2","vanpatten_east"],
    ["zim_coons","zim_english"],
    ["zim_english","ushers_zim"],
    ["ushers_zim", "zim_mill"],
    ["zim_mill","zim_round_lake"],
    ["zim_round_lake","zim_i87"],
    ["cp_center@VFerryRd","DawsLn@VFerryRd"],
    ["ushers_rt9","vanpatten_east"],
    ["vanpatten_east","ushers_ridge"],
    ["towpath_beach","oldCanal_ferry"],
    ["towpath_van_vranken","towpath_riverview"],
    ["towpath_riverview","towpath_end"],
    ["towpath_end","clutes"],
    ["clutes","riverview1"],
    ["riverview1","riverview"],
    ["riverview","towpath_beach"],
    ["146_9","route146_waypoint1"],
    ["route146_waypoint1","route146_waypoint2"],
    ["route146_waypoint2","route146_waypoint3"],
    ["route146_waypoint3","route146_waypoint4"],
    ["route146_waypoint4","route146_waypoint5"],
    ["route146_waypoint5","route146_waypoint6"],["route146_waypoint6","moe_146"],
    ["moe_146","route146_waypoint7"],
    ["route146_waypoint7","route146_waypoint8"],
    ["route146_waypoint8","route146_waypoint9"],
    ["route146_waypoint9","route146_waypoint10"],
    ["route146_waypoint10","146_146A"],
    ["moe_146","moe1"],
    ["moe1","moe2"],
    ["moe2","moe3"],
    ["moe3","moe4"],
    ["moe4","balsam_moe"],
    ["balsam1","balsam2"],
    ["balsam2","balsam3"],
    ["balsam3","balsam4"],
    ["balsam4","balsam5"],
    ["balsam5","balsam6"],
    ["balsam6","balsam7"],
    ["balsam7","balsam8"],
    ["balsam8","balsam9"],
    ["balsam9","balsam10"],
    ["balsam10","balsam11"],
    ["balsam11","balsam12"],
    ["avendale_sage","avendale"],
    ["avendale","avendale_turn"],
    ["avendale_turn","avendale1"],
    ["avendale1","avendale2"],
    ["avendale2","avendale3"],
    ["avendale3","avendale_path"],
    ["avendale_path","avendale4"],
    ["avendale4","avendale5"],
    ["avendale5","avendale6"],
    ["avendale6","avendale7"],
    ["avendale7","avendale8"],
    ["avendale8","avendale9"],
    ["avendale9","avendale10"],
    ["avendale10","avendale11"],
    ["avendale11","avendale12"],
    ["avendale12","avendale13"],
    ["avendale13","avendale14"],
    ["avendale14","avendale15"],
    ["avendale15","avendale16"],
    ["avendale16","avendale17"],
    ["avendale17","avendale18"],
    ["avendale18","avendale19"],
    ["avendale19","avendale20"],
    ["avendale20","avendale21"],
    ["avendale21","avendale22"],
    ["avendale22","avendale_i87"],
  ],
};